# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Graphics-Magick-ColorHistogramL
version:      1.00
version_from: ColorHistogram.pm
installdirs:  site
requires:
resources:
  repository: http://github.com/athomason/Graphics-Magick-ColorHistogram

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
resources:
    repository: git://github.com/athomason/Graphics-Magick-ColorHistogramL
